version: "3.8"
services:
  express_backend:
    container_name: express_backend
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - EXTERNAL_PORT=8080
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=db
      - PGHOST=postgres.host
      - PORT=3000
      - PGPORT=5432
    ports:
      - "3000:3000"
    links:
      - postgres:postgres.host
    # - redis
    command: npm run serve
    volumes:
      - .:/app
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
  redis-server:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - express_backend
    links:
      - express_backend
