version: "3.8"
services:
  express_backend:
    container_name: express_backend
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - EXTERNAL_PORT=8080
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=db
      - PGHOST=postgres.host
      - PORT=3000
      - PGPORT=5432
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nginx
      - postgres
    links:
      - postgres:postgres.host
      - redis
      - nginx
    working_dir: /app/
    command: npm run serve
    volumes:
      - .:/app
  postgres:
    restart: on-failure
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:80"

    command: 'bash -c "cat /etc/nginx/conf.d/express.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
