openapi: 3.0.1
info:
  contact:
    email: mikita.zdanovich@godeltech.com
  description: SDET MASTERY SANDBOX
  title: Godel Petstore
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://petstore.godel
paths:
  /pet:
    get:
      description: Retrieve list Pets
      operationId: getPets
      parameters:
        - description: Status values that need to be considered for filter
          in: query
          name: status
          required: false
          schema:
            items:
              default: available
              enum:
                - available
                - pending
                - sold
              type: string
            type: array
          style: form
        - description: ID of pet to return
          in: header
          name: id
          required: false
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pet'
                type: array
          description: Operation Succeed
      summary: Get All Pets
      tags:
        - pet
      x-eov-operation-handler: controllers/PetController
      x-eov-operation-id: getPets
    post:
      operationId: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "200":
          content: { }
          description: Pet Created Successfully
        "400":
          content: { }
          description: Invalid input
      security:
        - petstore_auth:
            - write:pets
            - read:pets
      summary: Add a new pet to the store
      tags:
        - pet
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/PetController
    delete:
      operationId: deletePet
      parameters:
        - explode: false
          in: header
          name: api_key
          required: true
          schema:
            type: string
          style: simple
        - description: Pet id to delete
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          content: { }
          description: Pet destroyed
        "400":
          content: { }
          description: Invalid ID sipplied
      security:
        - petstore_auth:
            - write:pets
            - read:pets
      summary: Deletes a pet
      tags:
        - pet
      x-eov-operation-handler: controllers/PetController
    put:
      operationId: updatePet
      description: Update an existing pet
      parameters:
        - description: ID of pet to return
          in: header
          name: id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "400":
          content: { }
          description: Invalid ID supplied
        "404":
          content: { }
          description: Pet not found
        "405":
          content: { }
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
      summary: Update an existing pet
      tags:
        - pet
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/PetController
  /pet/uploadImage:
    post:
      operationId: uploadFile
      parameters:
        - description: ID of pet to update
          explode: false
          in: query
          name: id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                additionalMetadata:
                  description: Additional data to pass to server
                  type: string
                file:
                  description: file to upload
                  format: binary
                  type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful operation
      security:
        - petstore_auth:
            - write:pets
            - read:pets
      summary: uploads an image
      tags:
        - pet
      x-eov-operation-handler: controllers/PetController
  /store/order:
    post:
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order placed for purchasing the pet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          content: { }
          description: Invalid Order
      summary: Place an order for a pet
      tags:
        - store
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/StoreController
  /store/order/{orderId}:
    delete:
      description: For valid response try integer IDs with positive integer value.
        Negative or non-integer values will generate API errors
      operationId: deleteOrder
      parameters:
        - description: ID of the order that needs to be deleted
          explode: false
          in: path
          name: orderId
          required: true
          schema:
            format: int64
            minimum: 1
            type: integer
          style: simple
      responses:
        "400":
          content: { }
          description: Invalid ID supplied
        "404":
          content: { }
          description: Order not found
      summary: Delete purchase order by ID
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
    get:
      description: For valid response try integer IDs with value >= 1 and <= 10. Other
        values will generated exceptions
      operationId: getOrderById
      parameters:
        - description: ID of pet that needs to be fetched
          explode: false
          in: path
          name: orderId
          required: true
          schema:
            format: int64
            maximum: 10
            minimum: 1
            type: integer
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          content: { }
          description: Invalid ID supplied
        "404":
          content: { }
          description: Order not found
      summary: Find purchase order by ID
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
  /store/inventory:
    get:
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: successful operation
      security:
        - api_key: [ ]
      summary: Returns pet inventories by status
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
  /user/createWithArray:
    post:
      operationId: createUsersWithArrayInput
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/User'
              type: array
        description: List of user object
        required: true
      responses:
        default:
          content: { }
          description: successful operation
      summary: Creates list of users with given input array
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
  /user/createWithList:
    post:
      operationId: createUsersWithListInput
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/User'
              type: array
        description: List of user object
        required: true
      responses:
        default:
          content: { }
          description: successful operation
      summary: Creates list of users with given input array
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
  /user/{username}:
    delete:
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - description: The name that needs to be deleted
          explode: false
          in: path
          name: username
          required: true
          schema:
            type: string
          style: simple
      responses:
        "400":
          content: { }
          description: Invalid username supplied
        "404":
          content: { }
          description: User not found
      summary: Delete user
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
    get:
      operationId: getUserByName
      parameters:
        - description: 'The name that needs to be fetched. Use user1 for testing. '
          explode: false
          in: path
          name: username
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          content: { }
          description: Invalid username supplied
        "404":
          content: { }
          description: User not found
      summary: Get user by user name
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
    put:
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - description: name that need to be updated
          explode: false
          in: path
          name: username
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
      responses:
        "400":
          content: { }
          description: Invalid user supplied
        "404":
          content: { }
          description: User not found
      summary: Updated user
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
  /user/login:
    get:
      operationId: loginUser
      parameters:
        - description: The user name for login
          explode: true
          in: query
          name: username
          required: true
          schema:
            type: string
          style: form
        - description: The password for login in clear text
          explode: true
          in: query
          name: password
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              explode: false
              schema:
                format: int32
                type: integer
              style: simple
            X-Expires-After:
              description: date in UTC when token expires
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content: { }
          description: Invalid username/password supplied
      summary: Logs user into the system
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
  /user/logout:
    get:
      operationId: logoutUser
      responses:
        default:
          content: { }
          description: successful operation
      summary: Logs out current logged in user session
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
  /user:
    post:
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
      responses:
        default:
          content: { }
          description: successful operation
      summary: Create user
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
components:
  schemas:
    ApiResponse:
      example:
        code: 0
        type: type
        message: message
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
      type: object
    Category:
      example:
        name: name
        id: 6
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
      xml:
        name: Category
    Pet:
      example:
        photoUrls:
          - photoUrls
          - photoUrls
        name: doggie
        category:
          name: name
          id: 6
        tags:
          - name: name
            id: 1
          - name: name
            id: 1
        status: available
      properties:
        category:
          $ref: '#/components/schemas/Category'
        name:
          example: doggie
          type: string
        photoUrls:
          items:
            type: string
            xml:
              name: photoUrl
          type: array
          xml:
            wrapped: true
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          xml:
            wrapped: true
        status:
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
          type: string
      required:
        - name
        - photoUrls
      type: object
      xml:
        name: Pet
    Tag:
      example:
        name: name
        id: 1
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
      xml:
        name: Tag
    Order:
      example:
        petId: 6
        quantity: 1
        id: 0
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: true
        status: placed
      properties:
        id:
          format: int64
          type: integer
        petId:
          format: int64
          type: integer
        quantity:
          format: int32
          type: integer
        shipDate:
          format: date-time
          type: string
        status:
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
          type: string
        complete:
          type: boolean
      type: object
      xml:
        name: Order
    User:
      example:
        firstName: firstName
        lastName: lastName
        password: password
        userStatus: 6
        phone: phone
        id: 0
        email: email
        username: username
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          description: User Status
          format: int32
          type: integer
      type: object
      xml:
        name: User
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: https://petstore.swagger.io/oauth/authorize
          scopes:
            read:pets: read your pets
            write:pets: modify pets in your account
      type: oauth2
